- hosts: all
  user: root
  become: True
  tasks:
   - name: Rsync datafiles backup
     copy:
        src: chrony.conf
        dest: /etc/chrony.conf
     delegate_to: "{{ inventory_hostname }}"
     register: results_rsync
